server:
  port: 8081


spring:
  datasource: # ?????
    url: jdbc:mysql://localhost:3306/gisdatabase?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

